platform :ios, '9.0'

def all_pods
  use_frameworks!

  pod 'FLEX', '~> 2.4', :configurations => ['debug']
  pod 'SwiftSoup', '2.2.0'
  pod 'Atributika', '4.8.2'
  pod 'PINRemoteImage'
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'FirebaseInstanceID', '2.0.0'
  pod 'MarqueeLabel'

end

target 'RTRS' do
  all_pods
end
