platform :ios, '9.0'

def all_pods
  use_frameworks!

  pod 'FLEX', '~> 2.4', :configurations => ['debug']
  pod 'SwiftSoup', '2.2.0'
  pod 'Atributika', '4.9.8'
  pod 'Firebase'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'FirebaseInstanceID'
  pod 'MarqueeLabel'
  pod 'MKToolTip'
  pod 'Protobuf', '3.11.4'

end

target 'RTRS' do
  all_pods
end
